--
-- PostgreSQL database dump
--

\restrict of2DM1oQuX9eCdSzSszKdGTYkEjoTejMHGgnHaxuXqGkSlY0WXZUkCFUYriyjMe

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_vendor boolean NOT NULL
);


ALTER TABLE public.account_customuser OWNER TO postgres;

--
-- Name: account_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.account_customuser_groups OWNER TO postgres;

--
-- Name: account_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.account_customuser_user_permissions OWNER TO postgres;

--
-- Name: account_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: inbox_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inbox_message (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    body text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.inbox_message OWNER TO postgres;

--
-- Name: inbox_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inbox_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inbox_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    order_number character varying(20) NOT NULL,
    full_name character varying(200) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    state character varying(100) NOT NULL,
    payment_method character varying(20) NOT NULL,
    total numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    payment_date timestamp with time zone,
    payment_reference character varying(100),
    payment_status character varying(20) NOT NULL
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO postgres;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL,
    image character varying(100)
);


ALTER TABLE public.product_category OWNER TO postgres;

--
-- Name: product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(50) NOT NULL,
    price numeric(10,2) NOT NULL,
    description text NOT NULL,
    main_image character varying(100),
    created_at timestamp with time zone NOT NULL,
    category_id bigint CONSTRAINT "product_product_Category_id_not_null" NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.product_product OWNER TO postgres;

--
-- Name: product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_productimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    product_id bigint CONSTRAINT "product_productimage_Product_id_not_null" NOT NULL
);


ALTER TABLE public.product_productimage OWNER TO postgres;

--
-- Name: product_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_review (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.product_review OWNER TO postgres;

--
-- Name: product_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_review (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reviews_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.reviews_review OWNER TO postgres;

--
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_wishlist (
    id bigint NOT NULL,
    added_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wishlist_wishlist OWNER TO postgres;

--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone_number, is_vendor) FROM stdin;
2	pbkdf2_sha256$1000000$Wnt9EfjS3365j304y7NGKM$5tjDKoUHE11364lktNFkAvNwJD64ZOtMAWFdKAFazEA=	\N	f	testuser			test@example.com	f	t	2025-12-28 13:53:30.731345+01		f
3	pbkdf2_sha256$1000000$fLXayhzyhvLnHU7QwYGZOt$UZzgVJG9TaRe40Zy7tMilBhScshv0FJM2qgWZ1tLx7c=	2025-12-28 13:55:48.941389+01	f	Mubazff			mojisolafolash123@gmail.com	f	t	2025-12-28 13:55:47.44841+01		f
1	pbkdf2_sha256$1000000$BitoCgc5D9rX2R86SuF5h1$qUbI9D7hxPCPhzEY7Zc6tSAVpnOsEUJuQ+nZK9NF+Ho=	2025-12-28 16:30:19.315871+01	t	Mahmud12			mahmudolasunkanmi895@gmail.com	t	t	2025-12-28 13:33:44.147846+01		f
4	pbkdf2_sha256$1000000$UrT3VFTKWxaylilmd7rzI7$ko0WIf4lW8aLiVrxlNfhSu1li5N/hI+Mbx88Belaj00=	\N	f	Mufazff			mojisolafolash123@gmail.com	f	t	2025-12-28 16:39:03.476946+01	08072410373	f
\.


--
-- Data for Name: account_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: account_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_customuser
22	Can change user	6	change_customuser
23	Can delete user	6	delete_customuser
24	Can view user	6	view_customuser
25	Can add order	7	add_order
26	Can change order	7	change_order
27	Can delete order	7	delete_order
28	Can view order	7	view_order
29	Can add order item	8	add_orderitem
30	Can change order item	8	change_orderitem
31	Can delete order item	8	delete_orderitem
32	Can view order item	8	view_orderitem
33	Can add wishlist	9	add_wishlist
34	Can change wishlist	9	change_wishlist
35	Can delete wishlist	9	delete_wishlist
36	Can view wishlist	9	view_wishlist
37	Can add category	10	add_category
38	Can change category	10	change_category
39	Can delete category	10	delete_category
40	Can view category	10	view_category
41	Can add product	11	add_product
42	Can change product	11	change_product
43	Can delete product	11	delete_product
44	Can view product	11	view_product
45	Can add product image	12	add_productimage
46	Can change product image	12	change_productimage
47	Can delete product image	12	delete_productimage
48	Can view product image	12	view_productimage
49	Can add review	13	add_review
50	Can change review	13	change_review
51	Can delete review	13	delete_review
52	Can view review	13	view_review
53	Can add message	14	add_message
54	Can change message	14	change_message
55	Can delete message	14	delete_message
56	Can view message	14	view_message
57	Can add review	15	add_review
58	Can change review	15	change_review
59	Can delete review	15	delete_review
60	Can view review	15	view_review
61	Can add vendor profile	16	add_vendorprofile
62	Can change vendor profile	16	change_vendorprofile
63	Can delete vendor profile	16	delete_vendorprofile
64	Can view vendor profile	16	view_vendorprofile
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-28 14:00:26.543503+01	1	Appliances	1	[{"added": {}}]	10	1
2	2025-12-28 14:01:17.397447+01	2	Phone & Tablet	1	[{"added": {}}]	10	1
3	2025-12-28 14:03:04.647348+01	3	Home	1	[{"added": {}}]	10	1
4	2025-12-28 14:03:54.145404+01	4	Gaming	1	[{"added": {}}]	10	1
5	2025-12-28 14:04:09.675524+01	5	Groceries	1	[{"added": {}}]	10	1
6	2025-12-28 14:05:01.794119+01	6	Electronics	1	[{"added": {}}]	10	1
7	2025-12-28 14:06:43.121721+01	7	Computing	1	[{"added": {}}]	10	1
8	2025-12-28 14:07:24.118136+01	8	Baby Products	1	[{"added": {}}]	10	1
9	2025-12-28 14:08:08.008065+01	9	Fashion	1	[{"added": {}}]	10	1
10	2025-12-28 14:12:37.998916+01	10	Jewelry & Beauty	1	[{"added": {}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	account	customuser
7	orders	order
8	orders	orderitem
9	wishlist	wishlist
10	product	category
11	product	product
12	product	productimage
13	product	review
14	inbox	message
15	reviews	review
16	account	vendorprofile
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-28 11:42:23.723507+01
2	contenttypes	0002_remove_content_type_name	2025-12-28 11:42:23.737381+01
3	auth	0001_initial	2025-12-28 11:42:23.790947+01
4	auth	0002_alter_permission_name_max_length	2025-12-28 11:42:23.795358+01
5	auth	0003_alter_user_email_max_length	2025-12-28 11:42:23.800351+01
6	auth	0004_alter_user_username_opts	2025-12-28 11:42:23.806675+01
7	auth	0005_alter_user_last_login_null	2025-12-28 11:42:23.813042+01
8	auth	0006_require_contenttypes_0002	2025-12-28 11:42:23.814757+01
9	auth	0007_alter_validators_add_error_messages	2025-12-28 11:42:23.819315+01
10	auth	0008_alter_user_username_max_length	2025-12-28 11:42:23.825399+01
11	auth	0009_alter_user_last_name_max_length	2025-12-28 11:42:23.830924+01
12	auth	0010_alter_group_name_max_length	2025-12-28 11:42:23.839124+01
13	auth	0011_update_proxy_permissions	2025-12-28 11:42:23.84518+01
14	auth	0012_alter_user_first_name_max_length	2025-12-28 11:42:23.849903+01
18	admin	0001_initial	2025-12-28 11:42:24.003609+01
19	admin	0002_logentry_remove_auto_add	2025-12-28 11:42:24.011266+01
20	admin	0003_logentry_add_action_flag_choices	2025-12-28 11:42:24.01744+01
21	inbox	0001_initial	2025-12-28 11:42:24.036718+01
22	product	0001_initial	2025-12-28 11:42:24.078121+01
23	product	0002_rename_category_product_category	2025-12-28 11:42:24.091844+01
24	product	0003_rename_product_productimage_product_and_more	2025-12-28 11:42:24.10443+01
25	orders	0001_initial	2025-12-28 11:42:24.133455+01
26	orders	0002_remove_order_country_remove_order_status_and_more	2025-12-28 11:42:24.208704+01
27	product	0004_review	2025-12-28 11:42:24.254228+01
28	product	0005_category_image	2025-12-28 11:42:24.259462+01
29	product	0006_product_owner	2025-12-28 11:42:24.276131+01
30	product	0007_alter_review_user	2025-12-28 11:42:24.287577+01
31	reviews	0001_initial	2025-12-28 11:42:24.315658+01
32	reviews	0002_alter_review_comment_alter_review_product_and_more	2025-12-28 11:42:24.346981+01
33	sessions	0001_initial	2025-12-28 11:42:24.360235+01
34	wishlist	0001_initial	2025-12-28 11:42:24.385165+01
35	wishlist	0002_wishlistitem_delete_wishlist	2025-12-28 11:42:24.418664+01
36	wishlist	0003_wishlist_delete_wishlistitem	2025-12-28 11:42:24.449533+01
37	wishlist	0004_alter_wishlist_user	2025-12-28 11:42:24.462409+01
38	account	0001_initial	2025-12-28 15:32:52.518526+01
39	account	0002_alter_vendorprofile_user	2025-12-28 16:34:24.92819+01
40	account	0003_alter_customuser_options_alter_vendorprofile_options_and_more	2025-12-28 16:46:45.053822+01
41	account	0004_alter_customuser_options_alter_vendorprofile_options_and_more	2025-12-28 16:58:10.3613+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
hz3su0q1ureacz5g3ucf7oz4i1g8nq4d	.eJxVjDkOwjAUBe_iGlmOt9iU9Jwh-hs4gBwpTirE3ZGlFNC-mXlvNcG-lWlvsk4zq7Ma1Ol3Q6Cn1A74AfW-aFrqts6ou6IP2vR1YXldDvfvoEArvU6YY8YQEWyCEYJ32ViEITCTu2VJbmRrM_kUjE0eSZxhLzkIkY1Ofb7kSTfb:1vZsip:_968g5zO6myzKi5V6NQ7IbAAuU8vhDVsyzjjI2RteQk	2026-01-11 16:30:19.326623+01
\.


--
-- Data for Name: inbox_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inbox_message (id, title, body, is_read, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, order_number, full_name, email, phone, address, state, payment_method, total, created_at, payment_date, payment_reference, payment_status) FROM stdin;
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_orderitem (id, price, quantity, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: product_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_category (id, name, slug, image) FROM stdin;
1	Appliances	appliances	category/Appl_kCkepW6..jpg
2	Phone & Tablet	phone-tablet	category/IMG_3991_LsTrn9G.JPG
3	Home	home	category/IMG_3906.JPG
4	Gaming	gaming	category/IMG_4134.JPG
5	Groceries	groceries	category/IMG_3945.JPG
6	Electronics	electronics	category/IMG_4070.JPG
7	Computing	computing	category/IMG_3996_r6TPItd.JPG
8	Baby Products	baby-products	category/IMG_4020_2Qdf6Uk.JPG
9	Fashion	fashion	category/IMG_3883_GZkDhOF.JPG
10	Jewelry & Beauty	jewelry-beauty	category/IMG_4199.JPG
\.


--
-- Data for Name: product_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_product (id, name, slug, price, description, main_image, created_at, category_id, owner_id) FROM stdin;
\.


--
-- Data for Name: product_productimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_productimage (id, image, product_id) FROM stdin;
\.


--
-- Data for Name: product_review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_review (id, rating, comment, created_at, product_id, user_id) FROM stdin;
\.


--
-- Data for Name: reviews_review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews_review (id, rating, comment, created_at, product_id, user_id) FROM stdin;
\.


--
-- Data for Name: wishlist_wishlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist_wishlist (id, added_at, product_id, user_id) FROM stdin;
\.


--
-- Name: account_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_customuser_groups_id_seq', 1, false);


--
-- Name: account_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_customuser_id_seq', 5, true);


--
-- Name: account_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_customuser_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 10, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: inbox_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inbox_message_id_seq', 1, false);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 1, false);


--
-- Name: product_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_category_id_seq', 10, true);


--
-- Name: product_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_product_id_seq', 1, false);


--
-- Name: product_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_productimage_id_seq', 1, false);


--
-- Name: product_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_review_id_seq', 1, false);


--
-- Name: reviews_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_review_id_seq', 1, false);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_wishlist_id_seq', 1, false);


--
-- Name: account_customuser_groups account_customuser_groups_customuser_id_group_id_7e51db7b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_customuser_id_group_id_7e51db7b_uniq UNIQUE (customuser_id, group_id);


--
-- Name: account_customuser_groups account_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: account_customuser account_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser
    ADD CONSTRAINT account_customuser_pkey PRIMARY KEY (id);


--
-- Name: account_customuser_user_permissions account_customuser_user__customuser_id_permission_650e378f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_user__customuser_id_permission_650e378f_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: account_customuser_user_permissions account_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: account_customuser account_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser
    ADD CONSTRAINT account_customuser_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inbox_message inbox_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inbox_message
    ADD CONSTRAINT inbox_message_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_order_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_order_number_key UNIQUE (order_number);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: product_category product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (id);


--
-- Name: product_category product_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_slug_key UNIQUE (slug);


--
-- Name: product_product product_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_pkey PRIMARY KEY (id);


--
-- Name: product_product product_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_slug_key UNIQUE (slug);


--
-- Name: product_productimage product_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_productimage
    ADD CONSTRAINT product_productimage_pkey PRIMARY KEY (id);


--
-- Name: product_review product_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_review
    ADD CONSTRAINT product_review_pkey PRIMARY KEY (id);


--
-- Name: reviews_review reviews_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_pkey PRIMARY KEY (id);


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_product_id_57695ed7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_product_id_57695ed7_uniq UNIQUE (user_id, product_id);


--
-- Name: account_customuser_groups_customuser_id_b6c60904; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_customuser_groups_customuser_id_b6c60904 ON public.account_customuser_groups USING btree (customuser_id);


--
-- Name: account_customuser_groups_group_id_2be9f6d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_customuser_groups_group_id_2be9f6d7 ON public.account_customuser_groups USING btree (group_id);


--
-- Name: account_customuser_user_permissions_customuser_id_03bcc114; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_customuser_user_permissions_customuser_id_03bcc114 ON public.account_customuser_user_permissions USING btree (customuser_id);


--
-- Name: account_customuser_user_permissions_permission_id_f4aec423; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_customuser_user_permissions_permission_id_f4aec423 ON public.account_customuser_user_permissions USING btree (permission_id);


--
-- Name: account_customuser_username_724ae020_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_customuser_username_724ae020_like ON public.account_customuser USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inbox_message_user_id_bba642aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inbox_message_user_id_bba642aa ON public.inbox_message USING btree (user_id);


--
-- Name: orders_order_order_number_4e985f70_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_order_number_4e985f70_like ON public.orders_order USING btree (order_number varchar_pattern_ops);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: product_category_slug_e1f8ccc4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_category_slug_e1f8ccc4_like ON public.product_category USING btree (slug varchar_pattern_ops);


--
-- Name: product_product_Category_id_bde4ff97; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "product_product_Category_id_bde4ff97" ON public.product_product USING btree (category_id);


--
-- Name: product_product_owner_id_af246414; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_product_owner_id_af246414 ON public.product_product USING btree (owner_id);


--
-- Name: product_product_slug_76cde0ae_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_product_slug_76cde0ae_like ON public.product_product USING btree (slug varchar_pattern_ops);


--
-- Name: product_productimage_Product_id_e2542d25; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "product_productimage_Product_id_e2542d25" ON public.product_productimage USING btree (product_id);


--
-- Name: product_review_product_id_428b0c5c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_review_product_id_428b0c5c ON public.product_review USING btree (product_id);


--
-- Name: product_review_user_id_101f565f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_review_user_id_101f565f ON public.product_review USING btree (user_id);


--
-- Name: reviews_review_product_id_ce2fa4c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_product_id_ce2fa4c6 ON public.reviews_review USING btree (product_id);


--
-- Name: reviews_review_user_id_875caff2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_review_user_id_875caff2 ON public.reviews_review USING btree (user_id);


--
-- Name: wishlist_wishlist_product_id_2d08b75d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_product_id_2d08b75d ON public.wishlist_wishlist USING btree (product_id);


--
-- Name: wishlist_wishlist_user_id_13f28b16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_wishlist_user_id_13f28b16 ON public.wishlist_wishlist USING btree (user_id);


--
-- Name: account_customuser_groups account_customuser_g_customuser_id_b6c60904_fk_account_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_g_customuser_id_b6c60904_fk_account_c FOREIGN KEY (customuser_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_groups account_customuser_groups_group_id_2be9f6d7_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_group_id_2be9f6d7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_user_permissions account_customuser_u_customuser_id_03bcc114_fk_account_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_u_customuser_id_03bcc114_fk_account_c FOREIGN KEY (customuser_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_user_permissions account_customuser_u_permission_id_f4aec423_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_u_permission_id_f4aec423_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inbox_message inbox_message_user_id_bba642aa_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inbox_message
    ADD CONSTRAINT inbox_message_user_id_bba642aa_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_product product_product_category_id_0c725779_fk_product_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_category_id_0c725779_fk_product_category_id FOREIGN KEY (category_id) REFERENCES public.product_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_product product_product_owner_id_af246414_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_owner_id_af246414_fk_account_customuser_id FOREIGN KEY (owner_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_productimage product_productimage_product_id_544084bb_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_productimage
    ADD CONSTRAINT product_productimage_product_id_544084bb_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_review product_review_product_id_428b0c5c_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_review
    ADD CONSTRAINT product_review_product_id_428b0c5c_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_review product_review_user_id_101f565f_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_review
    ADD CONSTRAINT product_review_user_id_101f565f_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_product_id_ce2fa4c6_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_product_id_ce2fa4c6_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_user_id_875caff2_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_user_id_875caff2_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_product_id_2d08b75d_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_product_id_2d08b75d_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_wishlist wishlist_wishlist_user_id_13f28b16_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_wishlist
    ADD CONSTRAINT wishlist_wishlist_user_id_13f28b16_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict of2DM1oQuX9eCdSzSszKdGTYkEjoTejMHGgnHaxuXqGkSlY0WXZUkCFUYriyjMe

